version: '3.1'

services:

  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_DATABASE: test-ngx
      MYSQL_USER: test-ngx
      MYSQL_PASSWORD: test-ngx
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/mysql:/var/lib/mysql
    ports:
        - "4306:3306"

  php:
    build: ./web
    volumes: 
      - ./web/public:/usr/share/nginx/html
      - ./web/log:/var/log/nginx/ 
    depends_on: ["db"]

  nginx:
    image: nginx:latest 
    volumes:
      - ./web/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./web/log:/var/log/nginx/ 
      - ./web/public:/usr/share/nginx/html
    restart: always
    ports: ["8080:80"]
    depends_on: ["php"]
